In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, KFold
# X ; Y; Z; Pressure; GripAngle; Timestamp; Test ID
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

from Utils import createFeatures, listPeopleArticle

In [2]:
path_control = [
    'data_motion/hw_dataset/control/C_0001.txt',
    'data_motion/hw_dataset/control/C_0002.txt',
    'data_motion/hw_dataset/control/C_0003.txt',
    'data_motion/hw_dataset/control/C_0004.txt',
    'data_motion/hw_dataset/control/C_0005.txt',
    'data_motion/hw_dataset/control/C_0006.txt',
    'data_motion/hw_dataset/control/C_0007.txt',
    'data_motion/hw_dataset/control/C_0008.txt',
    'data_motion/hw_dataset/control/C_0009.txt',
    'data_motion/hw_dataset/control/C_0010.txt',
    'data_motion/hw_dataset/control/C_0011.txt',
    'data_motion/hw_dataset/control/C_0012.txt',
    'data_motion/hw_dataset/control/C_0013.txt',
    'data_motion/hw_dataset/control/C_0014.txt',
    'data_motion/hw_dataset/control/C_0015.txt'
]


In [3]:
path_parkinson = [
    'data_motion/hw_dataset/parkinson/P_02100001.txt',
    'data_motion/hw_dataset/parkinson/P_02100002.txt',
    'data_motion/hw_dataset/parkinson/P_05060003.txt',
    'data_motion/hw_dataset/parkinson/P_05060004.txt',
    'data_motion/hw_dataset/parkinson/P_09100001.txt',
    'data_motion/hw_dataset/parkinson/P_09100003.txt',
    'data_motion/hw_dataset/parkinson/P_09100005.txt',
    'data_motion/hw_dataset/parkinson/P_11120003.txt',
    'data_motion/hw_dataset/parkinson/P_11120004.txt',
    'data_motion/hw_dataset/parkinson/P_11120005.txt',
    'data_motion/hw_dataset/parkinson/P_12060001.txt',
    'data_motion/hw_dataset/parkinson/P_12060002.txt',
    'data_motion/hw_dataset/parkinson/P_16100003.txt',
    'data_motion/hw_dataset/parkinson/P_16100004.txt',
    'data_motion/hw_dataset/parkinson/P_23100002.txt',
    'data_motion/hw_dataset/parkinson/P_23100003.txt',
    'data_motion/hw_dataset/parkinson/P_26060001.txt',
    'data_motion/hw_dataset/parkinson/P_26060002.txt',
    'data_motion/hw_dataset/parkinson/P_26060003.txt',
    'data_motion/hw_dataset/parkinson/P_26060006.txt',
    'data_motion/hw_dataset/parkinson/P_26060007.txt',
    'data_motion/hw_dataset/parkinson/P_27110001.txt',
    'data_motion/hw_dataset/parkinson/P_27110003.txt',
    'data_motion/hw_dataset/parkinson/P_30100001.txt',
    'data_motion/hw_dataset/parkinson/P_30100002.txt',
    'data_motion/new_dataset/parkinson/H_P000-0001.txt',
    'data_motion/new_dataset/parkinson/H_P000-0002.txt',
    'data_motion/new_dataset/parkinson/H_P000-0003.txt',
    'data_motion/new_dataset/parkinson/H_P000-0004.txt',
    'data_motion/new_dataset/parkinson/H_P000-0007.txt',
    'data_motion/new_dataset/parkinson/H_P000-0008.txt',
    'data_motion/new_dataset/parkinson/H_p000-0010.txt',
    'data_motion/new_dataset/parkinson/H_P000-0011.txt',
    'data_motion/new_dataset/parkinson/H_P000-0012.txt',
    'data_motion/new_dataset/parkinson/H_P000-0013.txt',
    'data_motion/new_dataset/parkinson/H_P000-0014.txt',
    'data_motion/new_dataset/parkinson/H_P000-0015.txt',
    'data_motion/new_dataset/parkinson/H_P000-0016.txt',
    'data_motion/new_dataset/parkinson/H_p000-0017.txt',
    'data_motion/new_dataset/parkinson/H_p000-0018.txt',
    'data_motion/new_dataset/parkinson/H_P000-0019.txt',
    'data_motion/new_dataset/parkinson/H_P000-0020.txt',
    'data_motion/new_dataset/parkinson/H_P000-0021.txt',
    'data_motion/new_dataset/parkinson/H_P000-0022.txt',
    'data_motion/new_dataset/parkinson/H_P000-0023.txt',
    'data_motion/new_dataset/parkinson/H_P000-0024.txt',
    'data_motion/new_dataset/parkinson/H_P000-0025.txt',
    'data_motion/new_dataset/parkinson/H_p000-0028.txt',
    'data_motion/new_dataset/parkinson/H_P000-0029.txt',
    'data_motion/new_dataset/parkinson/H_P000-0030.txt',
    'data_motion/new_dataset/parkinson/H_P000-0031.txt',
    'data_motion/new_dataset/parkinson/H_P000-0032.txt',
    'data_motion/new_dataset/parkinson/H_P000-0033.txt',
    'data_motion/new_dataset/parkinson/H_P000-0034.txt',
    'data_motion/new_dataset/parkinson/H_P000-0035.txt',
    'data_motion/new_dataset/parkinson/H_P000-0036.txt',
    'data_motion/new_dataset/parkinson/H_P000-0037.txt',
    'data_motion/new_dataset/parkinson/H_P000-0039.txt',
    'data_motion/new_dataset/parkinson/H_P000-0040.txt',
    'data_motion/new_dataset/parkinson/H_p000-0041.txt',
    'data_motion/new_dataset/parkinson/H_p000-0042.txt',
    'data_motion/new_dataset/parkinson/H_p000-0043.txt'
]

In [4]:
Fs = 133

In [5]:
listControl_0 = listPeopleArticle(path_control, Fs, 0)
listParkinson_0 = listPeopleArticle(path_parkinson, Fs, 0)
listControl_1 = listPeopleArticle(path_control, Fs, 1)
listParkinson_1 = listPeopleArticle(path_parkinson, Fs, 1)
listControl_2 = listPeopleArticle(path_control, Fs, 2)
listParkinson_2 = listPeopleArticle(path_parkinson, Fs, 2)

In [6]:
listControl_0, controlDiagnoses_0 = createFeatures(listControl_0, 0, 0)
listParkinson_0, parkinsonDiagnoses_0 = createFeatures(listParkinson_0, 1, 0)
listControl_1, controlDiagnoses_1 = createFeatures(listControl_1, 0, 1)
listParkinson_1, parkinsonDiagnoses_1 = createFeatures(listParkinson_1, 1, 1)
listControl_2, controlDiagnoses_2 = createFeatures(listControl_2, 0, 2)
listParkinson_2, parkinsonDiagnoses_2 = createFeatures(listParkinson_2, 1, 2)

In [7]:
print(f"Número de pessoas saudáveis no TestID 0: {listControl_0.shape[0]}")
print(f"Número de pessoas saudáveis no TestID 1: {listControl_1.shape[0]}")
print(f"Número de pessoas saudáveis no TestID 2: {listControl_2.shape[0]}")
print(f"Número de pessoas saudáveis no total: {listControl_0.shape[0]+listControl_1.shape[0]+listControl_2.shape[0]}")

Número de pessoas saudáveis no TestID 0: 15
Número de pessoas saudáveis no TestID 1: 15
Número de pessoas saudáveis no TestID 2: 7
Número de pessoas saudáveis no total: 37


In [8]:
print(f"Número de pessoas com Parkinson no TestID 0: {listParkinson_0.shape[0]}")
print(f"Número de pessoas com Parkinson no TestID 1: {listParkinson_1.shape[0]}")
print(f"Número de pessoas com Parkinson no TestID 2: {listParkinson_2.shape[0]}")
print(f"Número de pessoas com Parkinson no total: {listParkinson_0.shape[0]+listParkinson_1.shape[0]+listParkinson_2.shape[0]}")

Número de pessoas com Parkinson no TestID 0: 61
Número de pessoas com Parkinson no TestID 1: 57
Número de pessoas com Parkinson no TestID 2: 47
Número de pessoas com Parkinson no total: 165


In [9]:
listPerson = pd.concat([listControl_0, listParkinson_0,listControl_1,listParkinson_1,listControl_2,listParkinson_2])
listDiagnoses = np.concatenate([controlDiagnoses_0, parkinsonDiagnoses_0,controlDiagnoses_1,parkinsonDiagnoses_1,controlDiagnoses_2, parkinsonDiagnoses_2])

In [10]:
listPerson.head(10)

velocityWeighted  pressureWeighted           CISP
0        166.545769        898.051761  149566.721125
1        148.699103        793.014769  117920.585005
2        147.285197        850.331795  125241.286024
3        152.507921        897.886052  136934.734786
4        188.952987        935.801218  176822.435308
5        161.384234        848.482579  136931.711421
6        166.894042        896.585507  149634.779464
7        142.210509        629.639447   89541.346106
8        139.259830        744.507491  103679.986990
9        142.807156        877.717556  125344.347575

In [11]:
knnc = KNeighborsClassifier()
cartc = DecisionTreeClassifier()
rfc = RandomForestClassifier()

In [12]:
#n_splits = len(listPerson)
n_splits = 10

In [13]:
kf = KFold(n_splits=n_splits,shuffle=True)

In [14]:
kf.get_n_splits()

10

In [15]:
TP_TN_FP_FN = np.zeros((3,4))


for train_index, test_index in kf.split(listPerson,y=listDiagnoses):
    #print("TRAIN:", train_index, "TEST:", test_index)
    x_train, x_test = listPerson.iloc[train_index], listPerson.iloc[test_index]
    y_train, y_test = listDiagnoses[train_index], listDiagnoses[test_index]
    
    
    
    knnc_trained = knnc.fit(x_train, y_train)
    cartc_trained = cartc.fit(x_train, y_train)
    rfc_trained = rfc.fit(x_train, y_train)
    
    
    
    modelsc = [knnc_trained, cartc_trained, rfc_trained]

    j = 0
    for model in modelsc:
        predict = model.predict(x_test)
        
        for i in range(y_test.shape[0]):
            if y_test[i] == 0 and predict[i] == 0:
                TP_TN_FP_FN[j][1] +=1
            elif y_test[i] == 1 and predict[i] == 1:
                TP_TN_FP_FN[j][0] +=1
            elif y_test[i] == 1 and predict[i] == 0:
                TP_TN_FP_FN[j][3] +=1
            elif y_test[i] == 0 and predict[i] == 1:
                TP_TN_FP_FN[j][2] +=1
        j+=1
        #acc.append((TP+TN)/(TP+TN+FN+FP)*100)
        #sens.append((TP)/(TP+FN)*100)
        #esp.append((TN)/(TN+FP)*100)
    


In [16]:
TP_TN_FP_FN

array([[155.,  14.,  23.,  10.],
       [150.,  24.,  13.,  15.],
       [156.,  23.,  14.,   9.]])

In [17]:
acc = np.empty(3)
sens = np.empty(3)
esp = np.empty(3)
for i in range(3):
    TP,TN,FP,FN = TP_TN_FP_FN[i]
    acc[i] = ((TP+TN)/(TP+TN+FN+FP)*100)
    sens[i] = ((TP)/(TP+FN)*100)
    esp[i] = ((TN)/(TN+FP)*100)

In [18]:
acc,sens,esp

(array([83.66336634, 86.13861386, 88.61386139]),
 array([93.93939394, 90.90909091, 94.54545455]),
 array([37.83783784, 64.86486486, 62.16216216]))

In [19]:
mod = ['KNN','DecisionTree','RandomForest']
nam = ['acurácia','sensibilidade','especificidade']
for i in range(3):
    print(f'{mod[i]} sua {nam[0]} é de {np.round(acc[i],2)}%')
for i in range(3):
    print(f'{mod[i]} sua {nam[1]} é de {np.round(sens[i],2)}%')
for i in range(3):
    print(f'{mod[i]} sua {nam[2]} é de {np.round(esp[i],2)}%')

KNN sua acurácia é de 83.66%
DecisionTree sua acurácia é de 86.14%
RandomForest sua acurácia é de 88.61%
KNN sua sensibilidade é de 93.94%
DecisionTree sua sensibilidade é de 90.91%
RandomForest sua sensibilidade é de 94.55%
KNN sua especificidade é de 37.84%
DecisionTree sua especificidade é de 64.86%
RandomForest sua especificidade é de 62.16%
